{
 "title": "Haridy Production",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "haridy_http_requests_total" }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "haridy_http_errors_total" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 4 },
   "targets": [
    {
     "expr": "haridy_http_latency_average_microseconds"
    }
   ]
  }
 ]
}